### ISSUE TITLE
Container exiting

### ISSUE THREAD

**Issue by micha-kaiser** [jc9108/expanse#27]
When I try to run the container, it will stop with the following log:

```
> docker
> node -r dotenv/config controller/server.mjs dotenv_config_path=/data/.env_prod
node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^
Error: getaddrinfo ENOTFOUND undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined'
}
Node.js v19.2.0
```

Database is up & reachable, volume & env-file are available & readable, too. Am I missing something here?

**Comment by jc9108** [comment]
how are you running the container? this doesnt seem to be using the default setup/instructions. i see that the node version is 19.2.0 while expanse is currently using LTS, which is 18.12.1

please follow the [official setup and usage guide](https://github.com/jc9108/expanse/blob/main/README.md), and only make changes if you know what you are doing
