### ISSUE TITLE
Frontend Container never runs

### ISSUE THREAD

**Issue by tomtom215** [jc9108/expanse#3]
Just tried to clone the repo and follow the steps in your readme, however the frontend container never seems to come up. 

I've tried resetting and manually running commands from your run.sh script but it still is not successful. The frontend container never starts and shows no logs. The build and run process using your script has the error. Different line numbers are shown based on the run.sh command you use

> ./run.sh: line 30: return: can only `return' from a function or sourced script

**Comment by jc9108** [comment]
are you running the script exactly like it shows on the readme or are you running it by just calling the file name?

some related answers i found online::

![image](https://user-images.githubusercontent.com/31039318/189906492-203b8a2e-ce2e-46e9-9fea-478e992e0989.png)

![image](https://user-images.githubusercontent.com/31039318/189906583-b3180d38-c265-4216-8fdf-262f25716bd9.png)
