### ISSUE TITLE
unknown shorthand flag: 'f' in -f

### ISSUE THREAD

**Issue by moorsey** [jc9108/expanse#35]
Get this when running:

`sh ./run.sh prod up`

**Comment by sugoidogo** [comment]
https://github.com/docker/compose/issues/8986

Looks like this issue is mainly caused by docker installation issues. Can you double check you have docker-compose installed and up to date?

**Comment by sugoidogo** [comment]
Also, looks like a duplicate of #31 (with a better title)

**Comment by sugoidogo** [comment]
https://github.com/docker/compose/issues/8986#issuecomment-1266572352

Looks like you have compose v1, and you need compose v2. You may need to add upstream repos.

**Comment by jc9108** [comment]
install the [latest docker and docker compose for your platform](https://docs.docker.com/engine/install). it'll be `docker compose`, not `docker-compose`

**Comment by jc9108** [comment]
install the [latest docker engine and docker compose for your platform](https://docs.docker.com/engine/install). it'll be `docker compose`, not `docker-compose`
