### ISSUE TITLE
www.reddit.com/prefs/apps does not exist

### ISSUE THREAD

**Issue by dinsdalepiranha** [jc9108/expanse#37]
From `./backend/.env_prod`:
```
# go to https://www.reddit.com/prefs/apps ➔ "create another app..." ➔ name: "expanse", type: "web app", redirect uri: "http://localhost:1301/callback". then fill in these values
```
However this URL doesn't seem to exist (redirects you to reddit) and looking through "Settings" on reddit I am not seeing anything that allows me to create an app.

**Comment by sugoidogo** [comment]
Works fine for me on desktop, but not on mobile.

**Comment by compelledorphan** [comment]
Use old.reddit.com/prefs/apps
