### ISSUE TITLE
Use same api structure as reddit

### ISSUE THREAD

**Issue by FoxxMD** [jc9108/expanse#4]
I know this is a tall order but...

If you refactored the backend api endpoints to mirror the existing [reddit api](https://www.reddit.com/dev/api/), at least as a subset of the api, developers could use your application as a proxy. Basically as a cache using the same api. Would enable existing applications to leverage your app with only a URL change.

**Comment by jc9108** [comment]
sorry, just not really what this app was intended to do. all routes serving reddit data are protected on purpose as this is a private archiving tool

**Comment by FoxxMD** [comment]
I realize its not public. I meant as a private proxy so they wouldn't have to build their own cache. But ok.

**Comment by jc9108** [comment]
oh ok. still, this would not work just by changing the endpoints as currently data is sent through websocket to the client and not directly as an endpoint response. and im not planning to overhaul that for this
