### ISSUE TITLE
Expanse stuck at 57%

### ISSUE THREAD

**Issue by rivaborn** [jc9108/expanse#44]
I've installed Expanse on Ubuntu and authorized the application. When I go to the Expanse webpage, I click on "log in with reddit" and I am taken to the page where  I connect expanse to my reddit account. 

The page proceeds back to the expanse webpage and then the percentage on the screen increases gradually till it gets to 57%. It stays stuck at 57%. I have tried this on 3 separate Ubuntu installations with the same result.

Of note, I have 2 other reddit accounts that I used with expanse and that worked perfectly on the 3 Ubuntu installations. 

Is there a log that I could look at for errors? 

Thanks!

**Comment by rivaborn** [comment]
I checked the server after a week and it was working. I guess it just needed time. 

Closing this, Thanks!

p.s. for anyone wondering about logs, you can view docker logs using "docker logs -f service_name". Specifically in this case "docker logs -f expanse-app-1"

**Comment by jc9108** [comment]
shouldnt have taken a week, likely reddit api was degraded at the time. glad to hear its working tho
