### ISSUE TITLE
401 after OAuth

### ISSUE THREAD

**Issue by subzero355** [jc9108/expanse#7]
After I accept OAuth dialog, I get 401 returning to the app.
![image](https://user-images.githubusercontent.com/7847452/190081995-76a7946e-0a10-4b44-bb73-257fd1425e35.png)

**Comment by subzero355** [comment]
Log says, ```
new user (XXX)
saved user (XXX)
purged user (XXX)
denied user (XXX)

```

**Comment by jc9108** [comment]
maybe similar to #2

**Comment by subzero355** [comment]
Yes, works now, might be worth adding few notes to the Readme for helping starters. I can help with the documentation if you are fine

**Comment by jc9108** [comment]
i dont think it's necessary, i did specify in the env example. i will make it extra clear though, since 3 people have already made this syntax mistake so far
