### ISSUE TITLE
[Config] Using expanse with podman

### ISSUE THREAD

**Issue by 0fbcb238c0** [jc9108/expanse#9]
Bringing up the containers with `podman-compose` works as intended.
However, expanse_db_1 throws an error on start: "FATAL:  zero-length delimited identifier at or near """" at character 12".
This is due to the quotation marks around the three "POSTGRES" lines in the `.env_prod`
Remove the quotation marks and everything work perfectly.

I've verified, that the quotation marks are also not relevant in a docker context. It works with and without them, so they could be removed entirely from `.env_prod` which would make expanse work with podman and docker.

**Comment by jc9108** [comment]
i prefer having the quotes. ill add a note to the `.env_example` to let podman users know to remove the quotes. `.env_prod` isnt tracked anyways, so you only need to do it once
